apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: image-signer
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - serviceaccounts
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - 'image.openshift.io'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
