kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: image-signer
subjects:
  - kind: ServiceAccount
    name: image-signer
    namespace: kabanero
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: image-signer
