kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: signing-operator
subjects:
- kind: ServiceAccount
  name: signing-operator
  namespace: kabanero <<NEED TO BE MODIFIED>>
roleRef:
  kind: ClusterRole
  name: signing-operator
  apiGroup: rbac.authorization.k8s.io
